### ISSUE TITLE
[GRPHI-46] GameListCard 컴포넌트

### ISSUE THREAD

**Issue by joyswim** [Team-groupHi/grouphi-mvp-fe#25]
### 🎟️ 상위 작업 (Ticket Number)

GRPHI-17

### 🌳 브랜치명 (Branch)

feat/gameCard

### 📝 상세 내용(Description)

게임 카드 컴포넌트를 만듭니다.

### ✅ 체크리스트(Tasks)

- [ ] 게임 카드 컴포넌트 완성

**Comment by SoJuSo** [comment]
@joyswim 이 부분 게임 질문지 카드랑 약간 혼동될 수 있어서 컴포넌트 이름을 GameListCard로 바꾸면 어떨까요?
