### ISSUE TITLE
[GRPHI-76] UserInfoCard 컴포넌트

### ISSUE THREAD

**Issue by ksjdev** [Team-groupHi/grouphi-mvp-fe#54]
### 🎟️ 상위 작업 (Ticket Number)

GRPHI-64

### 🌳 브랜치명 (Branch)

feat/UserInfoCard

### 📝 상세 내용(Description)

UserInfoCard를 구현합니다.

### ✅ 체크리스트(Tasks)

- [ ] UserInfoCard 구현

**Comment by kim-hyunjoo** [comment]
대기실 페이지에 필요하여 제가 만들도록 하겠습니다!
